# Generated by Django 5.2.5 on 2025-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video_url",
        ),
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Products/videos/",
                verbose_name="Product 's Video",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(
                upload_to="Products/images/", verbose_name="Picture Image"
            ),
        ),
    ]
