# Generated by Django 5.2.5 on 2025-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_video_url_product_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Products/images/",
                verbose_name="Picture Image",
            ),
        ),
    ]
