# Generated by Django 5.2.5 on 2025-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_product_image_url_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/Products/images/",
                verbose_name="Picture Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/Products/videos/",
                verbose_name="Product 's Video",
            ),
        ),
    ]
