# Generated by Django 5.2.5 on 2025-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_image_alter_product_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="New Product?"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_off",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
