# Generated by Django 5.2.5 on 2025-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_is_new_product_is_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="off_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="off price",
            ),
        ),
    ]
